// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb3NkJnVjYqs-uhFSiH7NuXBAQFBIiHyo',
    appId: '1:21859136501:web:62ff43b5add88388cae6bc',
    messagingSenderId: '21859136501',
    projectId: 'ist-bug',
    authDomain: 'ist-bug.firebaseapp.com',
    storageBucket: 'ist-bug.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSTXkodirPcdo54YITJx_uw5xPdTLybHc',
    appId: '1:21859136501:android:e95b404e0579ae8ccae6bc',
    messagingSenderId: '21859136501',
    projectId: 'ist-bug',
    storageBucket: 'ist-bug.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnk7wprcRjGwUoS-sBw4_2ipzKd_kbzZg',
    appId: '1:21859136501:ios:bb895c4ad9c5ce31cae6bc',
    messagingSenderId: '21859136501',
    projectId: 'ist-bug',
    storageBucket: 'ist-bug.appspot.com',
    iosClientId: '21859136501-6q421kpcbif2ane3b9ncqehsp9ces1rp.apps.googleusercontent.com',
    iosBundleId: 'id.ist.istBug',
  );
}
